export const coin1 = new Audio();coin1.src = './assets/audio/redcoin1.mp3';coin1.volume = 0.3
export const coin2 = new Audio();coin2.src = './assets/audio/redcoin2.mp3';coin2.volume = 0.3
export const coin3 = new Audio();coin3.src = './assets/audio/redcoin3.mp3';coin3.volume = 0.3
export const coin4 = new Audio();coin4.src = './assets/audio/redcoin4.mp3';coin4.volume = 0.3
export const coin5 = new Audio();coin5.src = './assets/audio/redcoin5.mp3';coin5.volume = 0.3
export const coin6 = new Audio();coin6.src = './assets/audio/redcoin6.mp3';coin6.volume = 0.3
export const coin7 = new Audio();coin7.src = './assets/audio/redcoin7.mp3';coin7.volume = 0.3
export const coin8 = new Audio();coin8.src = './assets/audio/redcoin8.mp3';coin8.volume = 0.3
export const tunnelSound = new Audio();tunnelSound.src = './assets/audio/tunnelsound.mp3';tunnelSound.volume = 0.3
export const coinAudio = new Audio();coinAudio.src = './assets/audio/almostMario.mp3';coinAudio.volume = 0.4
export const deathAudio = new Audio();deathAudio.src = './assets/audio/death.mp3';deathAudio.volume = 0.4
export const yahooAudio = new Audio();yahooAudio.src = './assets/audio/yahoo3.wav';yahooAudio.volume = 0.4
export const hooAudio = new Audio();hooAudio.src = './assets/audio/hoohoo2.wav';hooAudio.volume = 0.4
export const grassAudio = new Audio();grassAudio.src = './assets/audio/step2.mp3';grassAudio.volume = 0.1
export const powerUp = new Audio();powerUp.src = './assets/audio/powerup.wav';powerUp.volume = 0.4
export const bumpAudio = new Audio();bumpAudio.src = './assets/audio/bump.wav';bumpAudio.volume = 0.4
export const brickAudio = new Audio();brickAudio.src = './assets/audio/brick.wav';brickAudio.volume = 0.6
export const sadMusic = new Audio();sadMusic.src = './assets/audio/sadmusic.mp3';sadMusic.volume = 0.3
export const goombyTalk1 = new Audio();goombyTalk1.src = './assets/audio/goombytalk1.mp3';goombyTalk1.volume = 0.3
export const goombyTalk2 = new Audio();goombyTalk2.src = './assets/audio/goombytalk2.mp3';goombyTalk2.volume = 0.3
export const goombyTalk3 = new Audio();goombyTalk3.src = './assets/audio/goombytalk3.mp3';goombyTalk3.volume = 0.3
export const hoorayAudio = new Audio();hoorayAudio.src = './assets/audio/hooray.mp3';hoorayAudio.volume = 0.3
export const yah = new Audio();yah.src = './assets/audio/yah1.wav';yah.volume = 0.2
export const bgMusic = new Audio();bgMusic.src = './assets/audio/bombomb.mp3';bgMusic.volume = 0.15
export const starAppear = new Audio();starAppear.src = './assets/audio/starAppear.mp3';starAppear.volume = 0.8
export const getStar = new Audio();getStar.src = './assets/audio/getstar2.mp3';getStar.volume = 0.6
export const almostMario = new Audio();almostMario.src = './assets/audio/almostMario.mp3';almostMario.volume = 0.6
export const selectSound = new Audio();selectSound.src = './assets/audio/selectionSound.wav';selectSound.volume = 0.3
export const okeyDokey = new Audio();okeyDokey.src = './assets/audio/okey.wav';okeyDokey.volume = 0.3
export const titleAudio = new Audio();titleAudio.src = './assets/audio/title.mp3';titleAudio.volume = 0.2
export const endMusic = new Audio();endMusic.src = './assets/audio/endMusic.mp3';endMusic.volume = 0.05
export const popsfx = new Audio();popsfx.src = './assets/audio/pop.mp3';popsfx.volume = 0.4
export const laughAudio = new Audio();laughAudio.src = './assets/audio/laugh.mp3';laughAudio.volume = 0.4
export const stompAudio = new Audio();stompAudio.src = './assets/audio/stomp.mp3';stompAudio.volume = 0.4
export const gameoverAudio = new Audio();gameoverAudio.src = './assets/audio/gameoverAudio.mp3';gameoverAudio.volume = 0.4
export const thankyou = new Audio();thankyou.src = './assets/audio/thankyou.wav';thankyou.volume = 0.4
export const success = new Audio();success.src = './assets/audio/success.mp3';success.volume = 0.4